### ISSUE TITLE
unable to get A2A retrievable accounts (from either bash or ps) using a cert user

### ISSUE THREAD

**Issue by sgundlach3** [OneIdentity/safeguard-ps#449] opened 2022-12-02 17:35 UTC
I have tried these  "Get retrievable accounts"  commands in order to get the API key of the retrievable accounts and I can t' get either work. I can however pull the API keys from swagger, share with customer so they can do an A2A call to retrieve the passwords.

Can someone help, so cert users can pull the API keys of the  retrievable accounts?

Here are the scripts that are NOT working:

--------
Powershell
--------

$mysystem=$args[0]
$myaccount=$args[1]

$certpass= Get-Content C:\Data\SGCerts\Dup\IgnioORT\certpwd.txt | ConvertTo-SecureString -AsPlainText -Force
$myAvailableAccts=Get-SafeguardA2aRetrievableAccount -Insecure -Appliance 150.172.116.3 -CertificateFile "C:\Data\SGCerts\DuP\ignioORT\ignioORT.p12" -Password $certpass
$myapikey = $myAvailableAccts | where {(($_.assetname -eq $mysystem) -and ($_.Accountname -eq $myaccount))} | % APIKey
Write-Host "apikey="$myapikey

Get-SafeguardA2aPassword -Insecure -Appliance 150.172.116.13 -CertificateFile "C:\Data\SGCerts\DuP\ignioORT\ignioORT.p12" -Password $certpass  -ApiKey $myapikey  

--------
**Safeguard-bash from Ubuntu**
--------

cpamops@CPAMNJWSDUP3:~/scripts$ echo | ./get-a2a-retrievable-account.sh -a 150.172.116.3 -c ibmaapi.cert.pem -k ibmaap
i.key.pem

Enter pass phrase for ibmaapi.key.pem:
[]
cpamops@CPAMNJWSDUP3:~/scripts$ echo | ./get-a2a-retrievable-account.sh -a 150.172.116.3 -c ibmaapi.cert.pem -k ibmaapi.key.pem -v3

Enter pass phrase for ibmaapi.key.pem:
[]

**Comment by petrsnd** [comment] 2022-12-02 19:28
We are investigating to determine the cause of the problem you are seeing.

**Comment by petrsnd** [comment] 2023-02-17 20:20
@sgundlach3 We have been unable to reproduce your issue on either Powershell or Bash.  Are you certain that your A2A registration is set up correctly?  Were you able to get this working?

**Comment by petrsnd** [comment] 2023-02-27 22:02
@sgundlach3 We were eventually able to reproduce this and identified it as a bug in SPP 7.1 and 7.0.1, where the API key information was mistakenly removed from the API response for certificate users.  This issue has been fixed in SPP 7.2 and 7.0.2.

**Closed** 2023-02-27 22:03 UTC

**Comment by sgundlach3** [comment] 2023-02-28 17:37
Thanks so much!!

Appreciate your efforts.

Is 7.0.2 now available?

Thanks again
Sherry

[Text  Description automatically generated]

From: petrsnd ***@***.***>
Date: Monday, February 27, 2023 at 5:03 PM
To: OneIdentity/safeguard-ps ***@***.***>
Cc: Sherry Gundlach ***@***.***>, Mention ***@***.***>
Subject: Re: [OneIdentity/safeguard-ps] unable to get A2A retrievable accounts (from either bash or ps) using a cert user (Issue #449)

@sgundlach3<https://github.com/sgundlach3> We were eventually able to reproduce this and identified it as a bug in SPP 7.1 and 7.0.1, where the API key information was mistakenly removed from the API response for certificate users. This issue has been fixed in SPP 7.2 and 7.0.2.

**Comment by petrsnd** [comment] 2023-03-01 00:14
@sgundlach3 It will be released for general availability very soon.  Current target date is tomorrow (3/1).  :)
