### ISSUE TITLE
Error installing module - signature of the file 'safeguard-ps.cat' is not valid.

### ISSUE THREAD

**Issue by oi-nam-presales** [OneIdentity/safeguard-ps#411] opened 2022-06-16 15:39 UTC
When I run  "Install-Module safeguard-ps" I get an error:

PackageManagement\Install-Package : The module 'safeguard-ps' cannot be installed or updated because the authenticode
signature of the file 'safeguard-ps.cat' is not valid.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9711 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters

**Comment by oi-nam-presales** [comment] 2022-06-21 22:44
```
Name             : ConsoleHost
Version          : 5.1.19041.1682
InstanceId       : 56913ccf-4336-498b-98cd-167177f1298d
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```
```
OS Name             : Microsoft Windows 10 Enterprise
OS Version          : 10.0.19044 N/A Build 19044
OS Manufacturer     : Microsoft Corporation
OS Configuration    : Standalone Workstation
OS Build Type       : Multiprocessor Free
System Boot Time    : 6/15/2022, 2:33:22 PM
System Manufacturer : Dell Inc.
System Model        : Precision 5510
System Type         : x64-based PC
System Directory    : C:\WINDOWS\system32
System Locale       : en-us;English (United States)
Hotfix(s)           : 11 Hotfix(s) Installed.,[01]: KB5013624,[02]: KB5000736,[03]: KB5003791,[04]: KB5014699,[05]:
                      KB5006753,[06]: KB5007273,[07]: KB5011352,[08]: KB5011651,[09]: KB5014032,[10]: KB5014035,[11]:
                      KB5005699
```

**Comment by petrsnd** [comment] 2022-07-06 16:01
It looks like there was a problem with the signature for 6.13.  Not sure of the cause...
Fixed in https://www.powershellgallery.com/packages/safeguard-ps/6.13.62641

**Closed by petrsnd** 2022-07-06 16:01 UTC
